# Generated by Django 3.1.3 on 2020-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_auto_20201201_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
